all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/carlos/.ssh/id_ed25519
    control_plane_endpoint: 192.168.1.8
    load_balancer_ip_pool:
      - 192.168.1.224/27

metal:
  children:
    masters:
      hosts:
        pvekubecontrolpane:
            ansible_host: 192.168.1.8
            mac: 'bc:24:11:4e:dc:39'
            disk: sda
            network_interface: ens18
        pvekubenode1:
          ansible_host: 192.168.1.10
          mac: 'BC:24:11:1C:E3:C0'
          disk: sda
          network_interface: ens18
        pvekubenode2:
          ansible_host: 192.168.1.12
          mac: 'BC:24:11:F7:CC:B8'
          disk: sda
          network_interface: ens18
        pvekubenode3:
          ansible_host: 192.168.1.11
          mac: 'BC:24:11:EB:C2:7D'
          disk: sda
          network_interface: ens18
      
    workers:
      hosts: {}
        
